champion_position_map = {'Aatrox': ['Top'], 'Ahri': ['Middle'], 'Akali': ['Top', 'Middle'], 
                         'Akshan': ['Middle'], 'Alistar': ['Support'], 'Ambessa': ['Middle'], 
                         'Amumu': ['Jungle', 'Support'], 'Anivia': ['Middle'], 'Annie': ['Middle'], 
                         'Aphelios': ['Bottom'], 'Ashe': ['Bottom', 'Support'], 'Aurelion Sol': ['Middle'], 
                         'Aurora': ['Top', 'Middle'], 'Azir': ['Middle'], 'Bard': ['Support'], 
                         "Bel'Veth": ['Jungle'], 'Blitzcrank': ['Support'], 'Brand': ['Jungle', 'Middle', 'Support'], 
                         'Braum': ['Support'], 'Briar': ['Jungle'], 'Caitlyn': ['Bottom'], 
                         'Camille': ['Top', 'Support'], 'Cassiopeia': ['Middle'], "Cho'Gath": ['Top'], 
                         'Corki': ['Middle'], 'Darius': ['Top'], 'Diana': ['Jungle', 'Middle'], 
                         'Dr. Mundo': ['Top'], 'Draven': ['Bottom'], 'Ekko': ['Jungle', 'Middle'], 
                         'Elise': ['Jungle'], 'Evelynn': ['Jungle'], 'Ezreal': ['Bottom'], 'Fiddlesticks': ['Jungle'], 
                         'Fiora': ['Top'], 'Fizz': ['Middle'], 'Galio': ['Middle', 'Support'], 'Gangplank': ['Top'], 
                         'Garen': ['Top'], 'Gnar': ['Top'], 'Gragas': ['Top', 'Jungle', 'Middle'], 
                         'Graves': ['Jungle'], 'Gwen': ['Top'], 'Hecarim': ['Jungle'], 
                         'Heimerdinger': ['Top', 'Middle', 'Support'], 'Hwei': ['Middle', 'Support'], 
                         'Illaoi': ['Top'], 'Irelia': ['Top', 'Middle'], 'Ivern': ['Jungle'], 'Janna': ['Support'], 
                         'Jarvan IV': ['Jungle'], 'Jax': ['Top', 'Jungle'], 'Jayce': ['Top', 'Middle'], 
                         'Jhin': ['Bottom'], 'Jinx': ['Bottom'], "K'Sante": ['Top'], "Kai'Sa": ['Bottom'], 
                         'Kalista': ['Bottom'], 'Karma': ['Top', 'Middle', 'Support'], 'Karthus': ['Jungle'], 
                         'Kassadin': ['Middle'], 'Katarina': ['Middle'], 'Kayle': ['Top'], 'Kayn': ['Jungle'], 
                         'Kennen': ['Top'], "Kha'Zix": ['Jungle'], 'Kindred': ['Jungle'], 'Kled': ['Top'], "Kog'Maw": ['Bottom'], 
                         'LeBlanc': ['Middle'], 'Lee Sin': ['Jungle'], 'Leona': ['Support'], 'Lillia': ['Jungle'], 'Lissandra': ['Middle'], 
                         'Lucian': ['Bottom'], 'Lulu': ['Support'], 'Lux': ['Middle', 'Support'], 'Malphite': ['Top', 'Middle', 'Support'], 
                         'Malzahar': ['Middle'], 'Maokai': ['Jungle', 'Support'], 'Master Yi': ['Jungle'], 'Mel': ['Middle'], 'Milio': ['Support'], 
                         'Miss Fortune': ['Bottom'], 'Mordekaiser': ['Top'], 'Morgana': ['Support'], 'Naafiri': ['Middle'], 'Nami': ['Support'], 
                         'Nasus': ['Top'], 'Nautilus': ['Support'], 'Neeko': ['Middle', 'Support'], 'Nidalee': ['Jungle'], 'Nilah': ['Bottom'], 
                         'Nocturne': ['Jungle'], 'Nunu & Willump': ['Jungle'], 'Olaf': ['Top'], 'Orianna': ['Middle'], 'Ornn': ['Top'], 
                         'Pantheon': ['Top', 'Jungle', 'Middle', 'Support'], 'Poppy': ['Top', 'Jungle'], 'Pyke': ['Support'], 'Qiyana': ['Middle'], 
                         'Quinn': ['Top'], 'Rakan': ['Support'], 'Rammus': ['Jungle'], "Rek'Sai": ['Jungle'], 'Rell': ['Support'], 
                         'Renata Glasc': ['Support'], 'Renekton': ['Top'], 'Rengar': ['Top', 'Jungle'], 'Riven': ['Top'], 'Rumble': ['Top', 'Middle'], 
                         'Ryze': ['Middle'], 'Samira': ['Bottom'], 'Sejuani': ['Jungle'], 'Senna': ['Bottom', 'Support'], 
                         'Seraphine': ['Bottom', 'Support'], 'Sett': ['Top'], 'Shaco': ['Jungle', 'Support'], 'Shen': ['Top', 'Support'], 
                         'Shyvana': ['Jungle'], 'Singed': ['Top'], 'Sion': ['Top'], 'Sivir': ['Bottom'], 'Skarner': ['Top', 'Jungle'], 
                         'Smolder': ['Top', 'Middle', 'Bottom'], 'Sona': ['Support'], 'Soraka': ['Support'], 'Swain': ['Middle', 'Support'], 
                         'Sylas': ['Top', 'Middle'], 'Syndra': ['Middle'], 'Tahm Kench': ['Top', 'Support'], 'Taliyah': ['Jungle', 'Middle'], 
                         'Talon': ['Jungle'], 'Taric': ['Middle', 'Support'], 'Teemo': ['Top', 'Jungle', 'Support'], 'Thresh': ['Support'], 
                         'Tristana': ['Middle', 'Bottom'], 'Trundle': ['Top', 'Jungle'], 'Tryndamere': ['Top'], 'Twisted Fate': ['Top', 'Middle', 'Bottom'], 
                         'Twitch': ['Bottom', 'Support'], 'Udyr': ['Top', 'Jungle'], 'Urgot': ['Top'], 'Varus': ['Bottom'], 'Vayne': ['Top', 'Bottom'],
                         'Veigar': ['Middle', 'Support'], "Vel'Koz": ['Middle', 'Support'], 'Vex': ['Middle'], 'Vi': ['Jungle'], 'Viego': ['Jungle'], 
                         'Viktor': ['Middle'], 'Vladimir': ['Top', 'Middle'], 'Volibear': ['Top', 'Jungle'], 'Warwick': ['Top', 'Jungle'], 
                         'Wukong': ['Top', 'Jungle'], 'Xayah': ['Bottom'], 'Xerath': ['Middle', 'Support'], 'Xin Zhao': ['Jungle'], 
                         'Yasuo': ['Top', 'Middle', 'Bottom'], 'Yone': ['Top', 'Middle'], 'Yorick': ['Top'], 'Yuumi': ['Support'], 
                         'Zac': ['Top', 'Jungle', 'Support'], 'Zed': ['Jungle', 'Middle'], 'Zeri': ['Bottom'], 'Ziggs': ['Middle', 'Bottom'], 
                         'Zilean': ['Support'], 'Zoe': ['Middle'], 'Zyra': ['Support']}

champion_id_map = {'Aatrox': 266, 'Ahri': 103, 'Akali': 84, 'Akshan': 166, 'Alistar': 12, 'Ambessa': 799, 'Amumu': 32, 
                   'Anivia': 34, 'Annie': 1, 'Aphelios': 523, 'Ashe': 22, 'AurelionSol': 136, 'Aurora': 893, 'Azir': 268, 
                   'Bard': 432, 'Belveth': 200, 'Blitzcrank': 53, 'Brand': 63, 'Braum': 201, 'Briar': 233, 'Caitlyn': 51, 
                   'Camille': 164, 'Cassiopeia': 69, 'Chogath': 31, 'Corki': 42, 'Darius': 122, 'Diana': 131, 'Draven': 119, 
                   'DrMundo': 36, 'Ekko': 245, 'Elise': 60, 'Evelynn': 28, 'Ezreal': 81, 'Fiddlesticks': 9, 'Fiora': 114, 
                   'Fizz': 105, 'Galio': 3, 'Gangplank': 41, 'Garen': 86, 'Gnar': 150, 'Gragas': 79, 'Graves': 104, 'Gwen': 887, 
                   'Hecarim': 120, 'Heimerdinger': 74, 'Hwei': 910, 'Illaoi': 420, 'Irelia': 39, 'Ivern': 427, 'Janna': 40, 
                   'JarvanIV': 59, 'Jax': 24, 'Jayce': 126, 'Jhin': 202, 'Jinx': 222, 'Kaisa': 145, 'Kalista': 429, 'Karma': 43, 
                   'Karthus': 30, 'Kassadin': 38, 'Katarina': 55, 'Kayle': 10, 'Kayn': 141, 'Kennen': 85, 'Khazix': 121, 'Kindred': 203, 
                   'Kled': 240, 'KogMaw': 96, 'KSante': 897, 'Leblanc': 7, 'LeeSin': 64, 'Leona': 89, 'Lillia': 876, 'Lissandra': 127, 
                   'Lucian': 236, 'Lulu': 117, 'Lux': 99, 'Malphite': 54, 'Malzahar': 90, 'Maokai': 57, 'MasterYi': 11, 'Mel': 800, 
                   'Milio': 902, 'MissFortune': 21, 'MonkeyKing': 62, 'Mordekaiser': 82, 'Morgana': 25, 'Naafiri': 950, 'Nami': 267, 
                   'Nasus': 75, 'Nautilus': 111, 'Neeko': 518, 'Nidalee': 76, 'Nilah': 895, 'Nocturne': 56, 'Nunu': 20, 'Olaf': 2, 
                   'Orianna': 61, 'Ornn': 516, 'Pantheon': 80, 'Poppy': 78, 'Pyke': 555, 'Qiyana': 246, 'Quinn': 133, 'Rakan': 497, 
                   'Rammus': 33, 'RekSai': 421, 'Rell': 526, 'Renata': 888, 'Renekton': 58, 'Rengar': 107, 'Riven': 92, 'Rumble': 68, 
                   'Ryze': 13, 'Samira': 360, 'Sejuani': 113, 'Senna': 235, 'Seraphine': 147, 'Sett': 875, 'Shaco': 35, 'Shen': 98, 
                   'Shyvana': 102, 'Singed': 27, 'Sion': 14, 'Sivir': 15, 'Skarner': 72, 'Smolder': 901, 'Sona': 37, 'Soraka': 16, 
                   'Swain': 50, 'Sylas': 517, 'Syndra': 134, 'TahmKench': 223, 'Taliyah': 163, 'Talon': 91, 'Taric': 44, 'Teemo': 17, 
                   'Thresh': 412, 'Tristana': 18, 'Trundle': 48, 'Tryndamere': 23, 'TwistedFate': 4, 'Twitch': 29, 'Udyr': 77, 'Urgot': 6, 
                   'Varus': 110, 'Vayne': 67, 'Veigar': 45, 'Velkoz': 161, 'Vex': 711, 'Vi': 254, 'Viego': 234, 'Viktor': 112, 'Vladimir': 8, 
                   'Volibear': 106, 'Warwick': 19, 'Xayah': 498, 'Xerath': 101, 'XinZhao': 5, 'Yasuo': 157, 'Yone': 777, 'Yorick': 83, 
                   'Yunara': 804, 'Yuumi': 350, 'Zac': 154, 'Zed': 238, 'Zeri': 221, 'Ziggs': 115, 'Zilean': 26, 'Zoe': 142, 'Zyra': 143}

if __name__ == "__main__":
    print(champion_position_map)